### ISSUE TITLE
Deployment to VPS

### ISSUE THREAD

**Issue by pmaojo** [spark-solutions/spark-starter-kit#10]
Hello. I´d like to use Capistrano to deploy the app to an VPS. Does this app have anything special to care when configuring Capistrano?

**Comment by damianlegawiec** [comment]
Hi @pmaojo - surely you can use it with Capistrano, things to remember:

1. Setting proper ENV values for the memcached cloud, sendgrid, S3, CDN and other present in secrets.yml and environments/production.rb
2. Precompile assets on deploy
3. Remove the "Heroku fix" section ( https://github.com/spark-solutions/spark-starter-kit/blob/master/Gemfile#L68 ) from Gemfile

**Comment by pmaojo** [comment]
Thankyou!

**Comment by pmaojo** [comment]
Hi, would the process be as a regular rails app? when I run passenger start, it does not run everything I need to use foreman...
