### ISSUE TITLE
ActiveRecord::NoDatabaseError: FATAL:  database "spark-starter-kit_development" does not exist - PG::ConnectionBad: FATAL:  database "spark-starter-kit_development" does not exist

### ISSUE THREAD

**Issue by elliotec** [spark-solutions/spark-starter-kit#100]
Having trouble getting Postgres to work. It's installed as is the project, but running it fails and outputs this error:

20:50:43 cache.1   | rake aborted! 20:50:43 cache.1   | ActiveRecord::NoDatabaseError: FATAL:  database "spark-starter-kit_development" does not exist 20:50:43 cache.1   | /Users/melliott/sparkSpree/spark-starter-kit/config/environment.rb:5:in `<top (required)>' 20:50:43 cache.1   | /Users/melliott/.rbenv/versions/2.3.1/bin/bundle:23:in `load' 20:50:43 cache.1   | /Users/melliott/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>' 20:50:43 cache.1   | PG::ConnectionBad: FATAL:  database "spark-starter-kit_development" does not exist 20:50:43 cache.1   | /Users/melliott/sparkSpree/spark-starter-kit/config/environment.rb:5:in `<top (required)>' 20:50:43 cache.1   | /Users/melliott/.rbenv/versions/2.3.1/bin/bundle:23:in `load' 20:50:43 cache.1   | /Users/melliott/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>' 20:50:43 cache.1   | Tasks: TOP => cache:clear => environment 20:50:43 cache.1   | (See full trace by running task with --trace)

Any idea what I can try?

**Comment by ridem** [comment]
What command did you use to initialize the project? `bin/setup`? This command should have created the database locally and populated it.

Otherwise, to set it up the DB:
```bash
rails db:migrate:reset
rails db:seed
```

I recommend running `bin/setup` from the project root though

**Comment by elliotec** [comment]
Yep, I used `bin/setup`, and tried both those commands already. Same error each time.

I'm thinking it's a Postgress problem rather than Rails but I've never had PG problems before and this seems unique to this project.
