### ISSUE TITLE
Heroku Review Apps support

### ISSUE THREAD

**Issue by damianlegawiec** [spark-solutions/spark-starter-kit#109]
- [ ] use Heroku App Name to compose assets and mailer URLs #140 
- [ ] create new bucket on S3 for each review APP
- [ ] setup separate memcached
- [ ] setup separate redis
- [ ] seed sample data

**Comment by muzykabart** [comment]
@damianlegawiec It works, but ENV vars like `APP_DOMAIN` cannot be automatically generated to match a new URL and it throws 404 errors cause of not found asset files
