### ISSUE TITLE
Currency symbol on Products page

### ISSUE THREAD

**Issue by wispmac** [spark-solutions/spark-starter-kit#119]
We are currently developing a site based on the spark-starter-kit. We have set up the store to use INR as the currency. All products have INR prices. Yet, the products page shows "$" symbol and the cart link on top right of the page also shows "$" symbol. Within the cart and products list within admin shows the Rupee symbol.

![image](https://cloud.githubusercontent.com/assets/2329537/24858322/829cfab2-1e09-11e7-8e9f-6399c410a532.png)
![image](https://cloud.githubusercontent.com/assets/2329537/24858339/92e00bee-1e09-11e7-98c8-1d8a696f03ae.png)
![image](https://cloud.githubusercontent.com/assets/2329537/24858353/a4da01f6-1e09-11e7-8dd0-295046e02cc9.png)
![image](https://cloud.githubusercontent.com/assets/2329537/24858365/ae89b228-1e09-11e7-90fb-25b28c4d4c91.png)
![image](https://cloud.githubusercontent.com/assets/2329537/24858379/bb694d64-1e09-11e7-851f-1875f4127b5b.png)
![image](https://cloud.githubusercontent.com/assets/2329537/24858428/eba14dd8-1e09-11e7-9030-fa38f72879bb.png)
![image](https://cloud.githubusercontent.com/assets/2329537/24858450/fdd95e96-1e09-11e7-91a9-6e28d04bfa4c.png)
![image](https://cloud.githubusercontent.com/assets/2329537/24858468/15dede9e-1e0a-11e7-87e3-00b7210d5007.png)
![image](https://cloud.githubusercontent.com/assets/2329537/24858482/2623457e-1e0a-11e7-947e-3d6a4ef15861.png)

**Comment by krzysiek1507** [comment]
Hi @wispmac We use [I18n-js](https://github.com/fnando/i18n-js) for displaying prices on Product Page and Products Index and probably we didn't configure it to work with other currencies than USD.

**Comment by wispmac** [comment]
Thanks. We have handled it.
