### ISSUE TITLE
Menu doesn't collapse on link click

### ISSUE THREAD

**Issue by pmaojo** [spark-solutions/spark-starter-kit#137]

**Comment by krzysiek1507** [comment]
Hi, @pmaojo. Which menu?

**Comment by pmaojo** [comment]
![captura de pantalla 2017-05-29 a las 16 35 49](https://cloud.githubusercontent.com/assets/411551/26555433/e7f0ac7a-448c-11e7-9cdd-ac043847a8fb.png)

The Navigation Menu
- home section
- Open menu
- Click on products
- Menú should collapse
