### ISSUE TITLE
react-rails 2.0

### ISSUE THREAD

**Issue by gbrlcustodio** [spark-solutions/spark-starter-kit#141]
Hey guys,

Is there any work in progress to migrate to react-rails v2? I know its been just two months since the gem v2 has been released, but, just for the sake. If there is no progress on it, I would be glad to contribute.

Thanks in advance.

**Comment by krzysiek1507** [comment]
Hi @gcmartins93. PR is welcome!

**Comment by gcmartins93** [comment]
Thanks @krzysiek1507, I'll spend some time this weekend to work on it. I've found some undocumented breaking change so far, but still struggling with others. Once it's done, I'll submit the PR.
