### ISSUE TITLE
Puma in cluster mode does not properly load translations (?)

### ISSUE THREAD

**Issue by delphaber** [spark-solutions/spark-starter-kit#150]
Hey,

I noticed this strange behaviour on my spree 3.3 application and I can replicate it here because you use puma too. I don't know why it happens and I don't know if it's a puma, spree, rails, i18n, mine problem 😭 

### The expectation

I want to change an english translation *already defined* in spree, e.g., `spree.quick_search`. So I edit `en.yml` to have something like this:

```yaml
 en:
   hello: "Hello world"
   spree:
     quick_search: "OVERRIDDEN QUICK SEARCH"
```

Then, when I visit `http://localhost:5000/admin/orders` I expect to see this:

![image](https://user-images.githubusercontent.com/139284/30378400-5737c6cc-9893-11e7-9a97-f113944a99e2.png)

### The problem

But instead I see this:

![image](https://user-images.githubusercontent.com/139284/30378442-7b0127ec-9893-11e7-8371-b4fdcb377a3c.png)

You see? `Quick search..` did not become `OVERRIDDEN QUICK SEARCH`.

### The fix (?)

After some hours of struggling, I noticed that if I run my rails app without Puma (or with Puma in single mode, no clustered mode) I can finally see `OVERRIDEN QUICK SEARCH` in the admin page.

Note: this happens in spree backend and spree frontend both.

### How to reproduce

I created a fork of this repo with two branches:

Here (https://github.com/delphaber/spark-starter-kit/tree/broken_test) you can test that the translation override won't work.

Here (https://github.com/delphaber/spark-starter-kit/tree/working_test) you can test that the translation override works.

## Final thoughts

It's a very very strange behaviour. Have you ever noticed it?

**Comment by weedySeaDragon** [comment]
Just a quick thought:  the I18n stuff is loaded _once_ early in the application.  Typically it's loaded when your `ApplicationController` class (instance) is loaded.  So unless/until you restart the application, you will not see new/changed I18n data.

Interaction with puma and spring will affect how and when the server info is reloaded, too.

Perhaps you've already taken this into account, but it's something that's not mentioned in the I18n documentation and trips up a lot of folks.

**Comment by delphaber** [comment]
Hi! I didn't think about `spring` because I usually `spring stop` already when something strange happens 😄 

Anyway I removed spring from Gemfile and made sure there was not any spring process alive, but https://github.com/delphaber/spark-starter-kit/tree/broken_test still does not show my overridden translation 😞
