### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by troias** [spark-solutions/spark-starter-kit#158]
Dont think this works anymore tried multiple times to run it and it fails.

**Comment by exocode** [comment]
I also followed the README. Ran "bin/setup" and fails by `PG::ConnectionBad`

````
 == Preparing database ==
[Scout] [10/10/18 08:22:37 +0200 MacBook-Pro.local (19054)] INFO : Couldn't find configuration in /Users/janjezek/Coding/RubymineProjects/spark-starter-kit/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
bin/rails:4:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments
(See full trace by running task with --trace)
[Scout] [10/10/18 08:22:39 +0200 MacBook-Pro.local (19060)] INFO : Couldn't find configuration in /Users/janjezek/Coding/RubymineProjects/spark-starter-kit/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"spark-starter-kit_development", "host"=>"localhost", "username"=>"postgres"}
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
bin/rails:4:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
[Scout] [10/10/18 08:22:42 +0200 MacBook-Pro.local (19066)] INFO : Couldn't find configuration in /Users/janjezek/Coding/RubymineProjects/spark-starter-kit/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
[Scout] [10/10/18 08:22:45 +0200 MacBook-Pro.local (19073)] INFO : Couldn't find configuration in /Users/janjezek/Coding/RubymineProjects/spark-starter-kit/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
bin/rails:4:in `<main>'
Tasks: TOP => db:abort_if_pending_migrations
(See full trace by running task with --trace)
```

Do I have to create a Dockerfile or change something in the config?

Any help would be appreciated

Thank you in advance

**Comment by exocode** [comment]
what helped me, was to use the "Docker for Mac" not my installed ones through Homebrew.....

**Comment by troias** [comment]
Mine says 

 == Starting docker-compose ==
Starting sparkstarterkitmaster_postgres_1 ... 
Starting sparkstarterkitmaster_memcached_1 ... 
Starting sparkstarterkitmaster_redis_1 ... 
Starting sparkstarterkitmaster_postgres_1
Starting sparkstarterkitmaster_memcached_1
Starting sparkstarterkitmaster_redis_1 ... error

ERROR: for sparkstarterkitmaster_redis_1  Cannot start service redis: driver failed programming external connectivity on endpoint sparkstarterkitmaster_redis_1 (44f1bc973fd7d35583e222a2f1ca7cf06c2feee14f52f4d35c82702528b7de49): Error startiStarting sparkstarterkitmaster_postgres_1 ... done

ERROR: for redis  Cannot start service redis: driver failed programming external connectivity on endpoint sparkstarterkitmaster_redis_1 (44f1bc973fd7d35583e222a2f1ca7cf06c2feee14f52f4d35c82702528b7de49): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use
ERROR: Encountered errors while bringing up the project.
== Installing dependencies ==
The git source `git://github.com/spree/spree.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/spree-contrib/spree_analytics_trackers.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The Gemfile's dependencies are satisfied
 
 == Installing node dependencies ==
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
 
 == Preparing database ==
[Scout] [10/11/18 19:41:12 +1300 troy-VirtualBox (30515)] INFO : Couldn't find configuration in /home/troy/Downloads/spark-starter-kit-master(2) (2)/spark-starter-kit-master/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:90:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:57:in `check_protected_environments!'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:13:in `block (2 levels) in <main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments
(See full trace by running task with --trace)
[Scout] [10/11/18 19:41:16 +1300 troy-VirtualBox (30535)] INFO : Couldn't find configuration in /home/troy/Downloads/spark-starter-kit-master(2) (2)/spark-starter-kit-master/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"spark-starter-kit_development", "host"=>"localhost", "username"=>"postgres"}
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:90:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:119:in `create'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
[Scout] [10/11/18 19:41:19 +1300 troy-VirtualBox (30550)] INFO : Couldn't find configuration in /home/troy/Downloads/spark-starter-kit-master(2) (2)/spark-starter-kit-master/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:90:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
[Scout] [10/11/18 19:41:22 +1300 troy-VirtualBox (30565)] INFO : Couldn't find configuration in /home/troy/Downloads/spark-starter-kit-master(2) (2)/spark-starter-kit-master/config/scout_apm.yml for environment: development. Configuration in ENV will still be applied.
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/home/troy/.rvm/gems/ruby-2.5.1/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:90:in `connection'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:177:in `block (2 levels) in <main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/troy/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/troy/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/troy/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:abort_if_pending_migrations
(See full trace by running task with --trace)

**Comment by troias** [comment]
any tips @damianlegawiec

**Comment by troias** [comment]
How do I fix "driver failed programming external connectivity on endpoint sparkstarterkitmaster_redis_1"

**Comment by troias** [comment]
never mind I sorted it. Excited to start working on this. Thanks team

**Comment by exocode** [comment]
I also found my way. I simply deleted everything, and reinstalled it, it worked. Thank you


```
git clone git@github.com:spark-solutions/spark-starter-kit.git
brew services stop postgresql
docker start
cd spark-starter-kit
rake db:drop # if you tried things before
bin/setup
bin/start
```
