### ISSUE TITLE
Upgrade of react-router-redux broke the app

### ISSUE THREAD

**Issue by ridem** [spark-solutions/spark-starter-kit#20]
Since latest commit, I can't get the app to work correctly, the rooting seems to dysfunction.
I used the Procfile.dev with no change on the repo.

On the client side, ClientApp.js throws: `Uncaught TypeError: (0 , _reactRouterRedux.routerMiddleware) is not a function`

**Comment by damianlegawiec** [comment]
@ridem those react-router-redux updates are crazy :confused:  Hope this is the last one, it's a micro library after all.
