### ISSUE TITLE
Replace Spree with Solidus

### ISSUE THREAD

**Issue by dt1973** [spark-solutions/spark-starter-kit#21]
Is this a possibility? Thanks!

**Comment by damianlegawiec** [comment]
@dt1973 not gonna happen ;) We won't go back to ancient & clunky admin panel of Spree 2.4, lack of Bootstrap and other great features of modern Spree versions. Living in the past is overrated. 

BTW. Spark Solutions is part of the Spree Core Team https://github.com/spree/spree/wiki/Core-Team

**Comment by orenf** [comment]
:+1:  for what it's worth

**Comment by dt1973** [comment]
But I thought Spree had been disintegrated and abandoned, even people on the core team (ie. Ryan Bigg) seems to recommend Solidus.

As for Bootstrap -- isn't that more for people who are too lazy and/or unable to come up with their own designs? Last time I checked it was full of messy class names and unnecessary grids/divs. At the Solidus Codemy YouTube intro (https://www.youtube.com/watch?v=0mxGzk1Lfwg) the guy adds Bootstrap in the matter of 2 seconds anyway.

**Comment by BenMorganIO** [comment]
As far as I can see, it's the Solidus team that's living in the future.

**Comment by dt1973** [comment]
I understand the story now. @damianlegawiec bought Spree after everyone had left in order for his ecommerce business to benefit from Spree's remaining brand recognition and reputation as one of the world's largest open source projects.

To the members of the former core team -- @radar, @schof, @joneslee85, @BDQ, @cmar, @LBRapid, @paulcc, @davidnorth and @romul -- are you guys ok with being listed on @damianlegawiec's site and hence used as pawns in his game? Shouldn't your names be listed on the Solidus site instead, considering it's the true continuation of Spree?

cc @JDUtil, @huoxito, @danabrit, @devilcoders, @peterberkenbosch, @GeekOnCoffee, @stephskardal, @parndt

**Comment by radar** [comment]
What site? What games?

This seems like drama generation for the sake of it. 

Show some facts instead of these essentially baseless accusations and then maybe you might get some backing.

I don't get why you're so mad.

**Comment by devilcoders** [comment]
@radar :+1:

**Comment by peterberkenbosch** [comment]
Yeah, let's cool down a bit. There is no harm done IMHO. Although I disagree with the comment about Solidus, let's just agree to disagree, keep it classy and move on with our lives :beers:

**Comment by damianlegawiec** [comment]
@dt1973 dude, what game? What pawns? We didn't buy spree. We (Spark Solutions + VinSol) just volunteered to maintain and develop Spree. For free. Because we have many clients using Spree. That's the whole story behind it.

**Comment by mradfaber** [comment]
@dt1973 You are entitled to your own opinions but there are rules of conduct you should read about: https://github.com/blog/2039-adopting-the-open-code-of-conduct

Show some respect to other people's time & effort - you are being disrespectful and xenophobic without any reason except for the fact that we (Spree Core Team) are trying to support Spree-based stores and their developers. It's a thankless job and we don't expect any thank-yous. But attacking us like that... I'm very disappointed in you as a reasonable adult. 

If you continue your ways I will be submitting your posts to GitHub admins as abusive both personally towards @damianlegawiec and in general (i.e. national origin). I am sure that open-source community will not tolerate any harassment of this sort. I'm sure I can expect Solidus community support in this matter.

I would rather agree to disagree. Thank you.
