### ISSUE TITLE
Live demo doesn't work?

### ISSUE THREAD

**Issue by oleksiidrobiazko** [spark-solutions/spark-starter-kit#28]
Hi, guys.  
Great job.  
Trying to checkout your application using [http://spark-starter-kit.herokuapp.com/](url).
When I click [http://spark-starter-kit.herokuapp.com/products](url) nothing happens.
When I click [http://spark-starter-kit.herokuapp.com/cart](url) I get 500 exception.
Thanks.
Have a good day.

**Comment by krzysiek1507** [comment]
Hi @oleksiidrobiazko Thanks for reporting. Fixed.
