### ISSUE TITLE
Error loading sample data

### ISSUE THREAD

**Issue by brettcrossley** [spark-solutions/spark-starter-kit#31]
When using a fresh install, I get an error on bootstrapping sample data. 
Command:
bundle exec rake db:bootstrap

Output:

Load Sample Data? [y/n]: y
Loaded Payment Methods samples
Loaded Shipping Categories samples
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "spree_shipping_methods_zones" does not exist
LINE 5:                WHERE a.attrelid = '"spree_shipping_methods_z...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"spree_shipping_methods_zones"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

Most relevant stack trace:
/Users/brett/.rvm/gems/ruby-2.2.4@spree_react/gems/spree_sample-3.1.0/lib/spree/sample.rb:13:in `load_sample'
/Users/brett/.rvm/gems/ruby-2.2.4@spree_react/gems/spree_sample-3.1.0/lib/spree_sample.rb:12:in `load_samples'
/Users/brett/.rvm/gems/ruby-2.2.4@spree_react/gems/spree_sample-3.1.0/lib/tasks/sample.rake:20:in `block (2 levels) in <top (required)>'
/Users/brett/.rvm/gems/ruby-2.2.4@spree_react/gems/spree_core-3.1.0/lib/tasks/core.rake:95:in `block (2 levels) in <top (required)>'

Interestingly enough, the relation table spree_shipping_method_zones does exist.

**Comment by chrisdobler** [comment]
As a temporary fix I added the migrations from the latest download of spree and it fixed the issue.

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spark-solutions/spark-starter-kit/pull/36
