### ISSUE TITLE
Understanding the scope of this project

### ISSUE THREAD

**Issue by chrisdobler** [spark-solutions/spark-starter-kit#56]
Hey guys, I've added a few commits to expand the feature set of this project. I was wondering if you would like me to send pull requests for these changes, or if you want to keep the project features more slim.

So far I have some pushes for these changes:
-Adding Radium
-Adding ability to include video files

Also, I was wondering about the possibility of adding more sample content to the home page as a sort of guide for how to add different content types.

Thanks

**Comment by ridem** [comment]
Cool! I'm very curious about how you integrated Radium!

I'm curious about the answer the Spark Solutions guys will give to this thread as well. I've been making "features" like extending the react part to the whole checkout process, cart panel, taxon views, turbolinks, and a few others.

I'd be happy to share it if the scope of the project is more than just having a boilerplate and can be  even more opinionated.

**Comment by chrisdobler** [comment]
Wow those features sound awesome ridem. I'd really like to see them regardless :)

**Comment by damianlegawiec** [comment]
Hi guys :)

Thanks for taking the interest in this project. We always welcome new PRs and features. 

The aim of this project is to get the best features every modern e-commerce project needs and which we cannot include in `spree` core (eg. we don't want to enforce `react` on all spree users).

@chrisdobler 
 - Radium - we didn't use it yet, currently we're sticking with `CSS modules` and `bootstrap-loader` but we'll take a look at it
 - Video files for products right? If so this could be even part of spree core I suppose. 

@ridem
 - we're very interested in those features you mentioned :)
 - we've been playing with turbolinks 5 in a few projects and working on getting the spree admin panel to use them in `3.2`
 - internally we're building react one-page checkouts/cart panels for our clients (a similar experiences to glossier/bonobos/etc) and we're thinking about doing a simple template that we can open source. 
 - new API endpoints are required which we'll be part of the next Spree release (`3.2`). Until then they will be included in this project

**Comment by ridem** [comment]
Hi Damian!

I played around with Radium, and it could be quite complementary with keeping the sass modules as they are right now. For example, I fetch additional content/pages from a headless CMS (Prismic, [check this repo](https://github.com/prismicio/reactjs-starter) - maybe another feature?), and setting the colors, media queries, and so on has been very easy thanks to Radium.

My checkout is also one page with three thirds, made with redux-form, Bonobos style.

I'd have to clean up a bit before submitting PRs, I'll be happy to do that in a few weeks.

**Comment by chrisdobler** [comment]
Hey @ridem, I've been having issues correctly inserting the Radium styleroot into this. How did you work that out?

**Comment by ridem** [comment]
Hi @chrisdobler,

You can wrap the StyleRoot in the layout for example, `js/layouts/index.js`

So it would be something like this:

```javascript
// your imports
import { StyleRoot } from 'radium';

export default (props) => {
  return (
      <StyleRoot>
        <HeaderContainer />
        <Flashes fixed={true}/>
        <main id="page">
          {props.children}
          <Footer />
        </main>
      </StyleRoot>
  )
}

```

**Comment by chrisdobler** [comment]
Thanks @ridem, do you know how I can include the user-agent? Radium always gives me a warning about that, but I'm not sure how to supply it.

**Comment by ridem** [comment]
Hi @chrisdobler, sorry for the delay.

Maybe we should put this discussion in another issue on this project. I think you can follow this link [https://github.com/FormidableLabs/radium/tree/master/docs/api#configuseragent](https://github.com/FormidableLabs/radium/tree/master/docs/api#configuseragent) to set it up. They provide an example as well. I'm providing the user agent in another way because I'm wrapping another provider upstream.

**Comment by chrisdobler** [comment]
- Dockerfile and docker-compose
- React Router Scroll fix

Would either of these be desired? I have the commits ready.

**Comment by denisinla** [comment]
@chrisdobler do you have a fork for docker setup for spark-starter-kit?
