### ISSUE TITLE
better error tracing?

### ISSUE THREAD

**Issue by chrisdobler** [spark-solutions/spark-starter-kit#61]
Hey Guys,

I'm having difficulty figuring out how to get a meaningful stack trace when I run into an error. The error messages seems to be related mostly to the rails app with a small message regarding the issue in the js which makes it difficult to figure out whats going on. Do you have any suggestions?

Thanks!

**Comment by krzysiek1507** [comment]
Hi @chrisdobler JavaScript is compiling [here](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L10). You can try to make error handling similar to `React::ServerRendering::PrerenderError` class
