### ISSUE TITLE
Any way to reduce the js compiled code? 1.1Mb is a reasonable size?

### ISSUE THREAD

**Issue by pmaojo** [spark-solutions/spark-starter-kit#65]
What do you think about http://stackoverflow.com/a/35100876 ?

**Comment by damianlegawiec** [comment]
@pmaojo with gzip compression it should reduce the size to ~200kb which is quite fine by nowaday standards. Webpack also lets us create additional bundles eg. lighter one for mobile

**Comment by pmaojo** [comment]
Thankyou for the answer.

**Comment by damianlegawiec** [comment]
@pmaojo this commit also helped a lot -> 87873f6c978f42517e742c79bdc0bfba1d27a8f4 :)

**Comment by pmaojo** [comment]
NIce
