### ISSUE TITLE
Best way to add Rails routes for static react pages

### ISSUE THREAD

**Issue by chrisdobler** [spark-solutions/spark-starter-kit#78]
Hey guys, What is the best way to add routes in Rails to catch static routes that I've defined in React? Better yet, is there any way to have Rails mirror React routes automatically?

**Comment by krzysiek1507** [comment]
Hi @chrisdobler. You can define routes in React [here](https://github.com/spark-solutions/spark-starter-kit/blob/master/client/js/routes/index.js). You can also use [js-routes](https://github.com/railsware/js-routes) for Rails URLs and paths on JS side. Unfortunately, I haven't seen any gem for that (you have to match route and component so it could be impossible to match it automatically).

**Comment by jshumakerpruitt** [comment]
@krzysiek1507 I'm trying to add routes that don't even need to hit the backend(they're totally static). I added routes in the js file you mentioned, but I get a rails routing error when I try to access the route (even if I get there using a `<Link>` from `react-router`).  

I'm actually not that familiar with `react-rails`. I usually use rails with `--api` and keep my frontend in a separate repo.  Is there some way I can let `react-router` take over in cases like this?  Maybe a wildcard route that always renders `<App>`?

**Comment by krzysiek1507** [comment]
@jshumakerpruitt your Rails application has to handle route because HTML requests are always handled by the backend.

**Comment by jshumakerpruitt** [comment]
@krzysiek1507 I tried adding a route for static pages, but I get an error from app/views/shared/_header.haml:  

```
Started GET "/static" for ::1 at 2016-11-14 15:29:26 +0700
Processing by StaticPagesController#index as HTML
  Rendered static_pages/index.html.erb within layouts/application (0.5ms)
  Rendered shared/_head.haml (1415.4ms)
Completed 500 Internal Server Error in 1446ms (ActiveRecord: 0.0ms)

NameError - undefined local variable or method `meta_data_tags' for #<#<Class:0x007f986529fba8>:0x007f9862f80c08>:
  app/views/shared/_head.haml:5:in `_c6c7ad771ce3aac0f3a74451353e9b18'
  actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:143:in `render'
```

**Comment by krzysiek1507** [comment]
@jshumakerpruitt please try to include [`Spree::BaseHelper`](https://github.com/spree/spree/blob/3-1-stable/core/app/helpers/spree/base_helper.rb) in your controller

**Comment by jshumakerpruitt** [comment]
@krzysiek1507  I added `helper Spree::BaseHelper` to the controller, but then I got a `undefined local variable or method 'current_store' for #<#<Class:0x007f80e49541d0>:0x007f80e5962b58>
` error, so I added `include Spree::Core::ControllerHelpers::Store` and it worked. Thanks again!

**Comment by chrisdobler** [comment]
Thanks @krzysiek1507, I'm trying to figure out on the Rails side. Is it possible to use with spree-contrib/spree_static_content? I tried this method, but only get a blank page when it renders the view.
