### ISSUE TITLE
Integration with spree_braintree_vzero

### ISSUE THREAD

**Issue by jshumakerpruitt** [spark-solutions/spark-starter-kit#85]
[spree_braintree_vzero](https://github.com/spree-contrib/spree_braintree_vzero) expects a slightly different file structure.  I got `bundle exec rails g spree_braintree_vzero:install` to work by adding a `vendor/assets/javascripts/spree/backend/all.js` and `vendor/assets/stylesheets/spree/backend/all.css`.  The command added a require statement to each file: ` *= require spree/backend/spree_braintree_vzero` and `//= require spree/backend/spree_braintree_vzero` for all.css and all.js respectively.  

I copied these lines to `app/assets/stylesheets/application.dev.scss` and `app/assets/javascripts/application.dev.js`

When I try checkout on my heroku site everything works until the final screen when I get a server error page and this message in the logs:  

```
2016-11-12T13:46:45.267936+00:00 app[web.1]:
2016-11-12T13:46:45.267938+00:00 app[web.1]: Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
2016-11-12T13:46:45.267939+00:00 app[web.1]:   lib/cloud_flare_middleware.rb:18:in `call'
2016-11-12T13:46:45.267940+00:00 app[web.1]:
2016-11-12T13:46:45.267940+00:00 app[web.1]:
```

Which is weird since redis isn't even mentioned in the gemfile.

**Comment by damianlegawiec** [comment]
Hi @	jshumakerpruitt can you paste full output? Actually we wrote the Braintree extension ;) Redis is required for ActiveJob (sidekiq)

**Comment by krzysiek1507** [comment]
Hi @jshumakerpruitt Have you added Redis to your heroku app? Spree requires redis on Order Confirmation Page.

**Comment by jshumakerpruitt** [comment]
@krzysiek1507 @damianlegawiec Thanks for the quick response.  I added redis to heroku and everything worked fine.  This repo and spree_braintree_vzero are awesome. Thanks
