### ISSUE TITLE
JS runtime: "upgrade" to mini_racer

### ISSUE THREAD

**Issue by ridem** [spark-solutions/spark-starter-kit#98]
Why not upgrade the ExecJS runtime to `mini_racer`? I use it on my react-rails projects and it's making server rendering much more efficient.
`react_on_rails` have themselves moved to using it instead of `therubyracer`. Plus it fixed my `setTimeout` polyfill console errors that were coming from `babel-polyfill`.

Resources:
- http://marianposaceanu.com/articles/making-rails-asset-pipeline-faster
- https://github.com/shakacode/react_on_rails/issues/501

If you read the first link, you may also be tempted to try `sassc-rails`. If you have gems that depend on `sass-rails`, here's a way to add it:
https://github.com/sass/sassc-rails/issues/68#issuecomment-278084323

**Comment by krzysiek1507** [comment]
Hi @ridem. We use `mini_racer` in 2 projects and we want to be sure that it works correctly in all cases.
`react-rails` 1.10.0 polyfills `setTimeout`.

**Comment by krzysiek1507** [comment]
Closed with #102
