### ISSUE TITLE
Rails 5: some dependencies are not needed anymore

### ISSUE THREAD

**Issue by ridem** [spark-solutions/spark-starter-kit#99]
Suggestion over some dependency removals, since the project is now Rails 5:

`rails_12factor`:
https://github.com/heroku/rails_12factor#rails-5
(Same for `font assets`, it's not needed anymore)

**Comment by krzysiek1507** [comment]
Hi @ridem, PR is welcome.

**Comment by krzysiek1507** [comment]
@ridem could you please link to article about Rails 5 and `font_assets`?
